//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.10 at 12:36:52 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://quickcomp.com/quickcomp/soap/entities/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.quickcomp.soapclient.wsdll;
